#The output of this program will be the numbers 0,1,.....,99, each printed on its own line.
for i in range(100):
    print(i)

#since the loop variable, i, gets increased 1 each time through the loop, it can be used to keep track of where we are in the looping process.

for i in range(3):
    print(i+1, '-- Hello')

#There is nothing too special about the name i for our variable.

for wacky_name in range(100):
    print(wacky_name)
#It's a convenion in programming to use the letters i, j, and k for loop variables,unless there's a good reason to give the variable a more descriptive name.
#  